# Generated by Django 4.2.11 on 2024-10-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
