# Generated by Django 4.2.11 on 2024-10-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymentmethod_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.paymentmethod'),
        ),
    ]
