# Generated by Django 4.2.11 on 2024-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default='1', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
