# Generated by Django 4.2.11 on 2024-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'On'), ('0', 'Off')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='Categories/photos/%y/%m/%d'),
        ),
    ]
