# Generated by Django 4.2.11 on 2024-11-01 19:21

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('products', '0003_alter_brand_logo_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
