# Generated by Django 4.2.11 on 2024-10-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_status_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Categories/photos/%y/%m/%d'),
        ),
    ]
