# Generated by Django 4.2.11 on 2024-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_attribute_subattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='subattribute',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
