# Generated by Django 4.2.11 on 2024-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'On'), ('0', 'Off')], default='off', max_length=1),
        ),
    ]
